apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Zomato
  name: Zomato-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: Zomato
  template:
    metadata:
      labels:
        app: Zomato
    spec:
      containers:
      - name: cont1
        image: rahamshaik/zomatoproject:myzomatoimage
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: Zomato
  ports:
    - port: 80
